# yaml-language-server: $schema=../../../../../symfony/dependency-injection/Loader/schema/services.schema.json
services:
    _defaults:
        autowire: true
        autoconfigure: true

    KikCMS\Command\App\UpCommand:
        arguments:
            $id: '%app.id%'
            $name: '%app.name%'
            $portBase: '%app.portBase%'

    KikCMS\Command\App\DownCommand:
        arguments:
            $id: '%app.id%'
            $name: '%app.name%'
            $portBase: '%app.portBase%'

    KikCMS\Command\App\AttachCommand:
        arguments:
            $name: '%app.name%'

    KikCMS\Command\Cms\UpCommand:
        arguments:
            $name: '%cms.name%'
            $port: '%cms.port%'

    KikCMS\Command\Cms\DownCommand:
        arguments:
            $name: '%cms.name%'
            $port: '%cms.port%'

    KikCMS\Command\Cms\AttachCommand:
        arguments:
            $name: '%cms.name%'