services:
  php:
    image: kiksaus/kikdev-symfony
    ports:
      - "${PORT}:443"
    volumes:
      - ./../:/var/www:cached
      - ./../var/certs:/var/www/certs:cached
      - ./../public_html/:/var/www/public_html:cached
    networks:
      kikdev:
        aliases:
          - ${ALIAS}
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.host.internal

networks:
  kikdev:
    external: true
    name: kikdev