controllers_domain:
    resource:
        path: ../src/Domain
        namespace: KikCMS\Domain
    type: attribute

controllers_entity:
    resource:
        path: ../src/Entity
        namespace: KikCMS\Entity
    type: attribute

reset:
    path: /cms/login/password-reset/{user}/{id}/{key}