tabs:
    -   key: general
        name: General
        fields:
            darkmode:
                type: select
                field: settings.cms.darkmode
                items:
                    -   key: default
                        value: System
                    -   key: light
                        value: Light
                    -   key: dark
                        value: Dark
                label: Darkmode
                special: darkModeSelect
                store: false

    -   key: advanced
        name: Advanced
        fields:
            settings.cms.text1:
                type: text
                label: Open field

            settings.cms.text2:
                key: field2
                type: text
                label: Another open field (required)
                validator:
                    name: presence
                    parameters: { }

            settings.cms.hobbies:
                type: datatable
                label: Hobbies
                instance: hobbies
                settings: this.appMocker.dataTableMock.subDataTableData

        save: true

name: settings
source:
    type: keyValue